// src/lib/design/components/WhatsAppDrawer.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n';
  import type { Snippet } from 'svelte';
  import { getCommsBaseUrl } from '$lib/api/comms';
  import AltchaWidget from './AltchaWidget.svelte';

  interface Props {
    trigger: Snippet<[() => void]>;
  }

  let { trigger }: Props = $props();

  type Status = 'idle' | 'submitting' | 'success' | 'error';

  let open = $state(false);
  let name = $state('');
  let phone = $state('');
  let message = $state('');
  let altchaPayload = $state<string | null>(null);
  let status = $state<Status>('idle');

  const commsBase = getCommsBaseUrl();
  const challengeUrl = `${commsBase}/api/altcha-challenge`;

  function reset() {
    name = '';
    phone = '';
    message = '';
    altchaPayload = null;
    status = 'idle';
  }

  function close() {
    open = false;
    reset();
  }

  async function handleSubmit(ev: SubmitEvent) {
    ev.preventDefault();

    if (!altchaPayload) {
      status = 'error';
      return;
    }

    status = 'submitting';

    try {
      const res = await fetch(`${commsBase}/api/contact`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          email: '',
          phone: phone || undefined,
          message: message || 'Contato solicitado via WhatsApp',
          whatsapp_opt_in: true,
          altcha: altchaPayload,
          source: 'whatsapp',
          language: $_('common.languageCode') ?? 'pt'
        })
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      status = 'success';
    } catch {
      status = 'error';
    }
  }
</script>

{@render trigger(() => (open = true))}

{#if open}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    class="overlay"
    role="presentation"
    tabindex="-1"
    onclick={close}
    onkeydown={(e) => e.key === 'Escape' && close()}
  >
    <div
      class="drawer"
      role="dialog"
      aria-modal="true"
      aria-labelledby="wa-title"
      tabindex="-1"
      onclick={(e) => e.stopPropagation()}
    >
      <div class="hairline"></div>

      <div class="header">
        <div>
          <h2 id="wa-title">{$_('contact.whatsappLabel')}</h2>
          <p>{$_('contact.body')}</p>
        </div>
        <button type="button" class="close" onclick={close} aria-label={$_('common.close')}>
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            class="icon-small"
          >
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>

      {#if status === 'success'}
        <div class="success">
          <div class="icon-wrap">
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              class="icon"
            >
              <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
              <polyline points="22 4 12 14.01 9 11.01" />
            </svg>
          </div>
          <p>{$_('contact.form.success')}</p>
          <button type="button" class="rbx-cta" onclick={close}>{$_('common.close')}</button>
        </div>
      {:else}
        <form class="form" onsubmit={handleSubmit}>
          <div class="field">
            <label for="wa-name">{$_('contact.form.name')} *</label>
            <input
              id="wa-name"
              type="text"
              required
              bind:value={name}
              placeholder={$_('contact.form.namePlaceholder')}
            />
          </div>

          <div class="field">
            <label for="wa-phone">WhatsApp *</label>
            <input
              id="wa-phone"
              type="tel"
              required
              bind:value={phone}
              placeholder={$_('contact.form.phonePlaceholder')}
            />
          </div>

          <div class="field">
            <label for="wa-message">{$_('contact.form.message')}</label>
            <textarea
              id="wa-message"
              rows="3"
              bind:value={message}
              placeholder={$_('contact.form.messagePlaceholder')}
            ></textarea>
          </div>

          <AltchaWidget
            challengeurl={challengeUrl}
            on:statechange={(ev) => (altchaPayload = ev.detail)}
          />

          {#if status === 'error'}
            <div class="error" role="alert">
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                class="icon-small"
              >
                <circle cx="12" cy="12" r="10" />
                <line x1="12" y1="8" x2="12" y2="12" />
                <line x1="12" y1="16" x2="12.01" y2="16" />
              </svg>
              <span>{$_('contact.form.error')}</span>
            </div>
          {/if}

          <button type="submit" class="submit" disabled={status === 'submitting'}>
            {#if status === 'submitting'}
              <span class="spinner"></span>
              <span>{$_('contact.form.submitting')}</span>
            {:else}
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                class="icon-small"
              >
                <line x1="22" y1="2" x2="11" y2="13" />
                <polygon points="22 2 15 22 11 13 2 9 22 2" />
              </svg>
              <span>{$_('contact.form.submit')}</span>
            {/if}
          </button>
        </form>
      {/if}
    </div>
  </div>
{/if}

<style>
  .overlay {
    position: fixed;
    inset: 0;
    z-index: 50;
    background: rgba(7, 8, 10, 0.72);
    backdrop-filter: blur(4px);
    display: flex;
    justify-content: flex-end;
  }

  .drawer {
    position: relative;
    width: 100%;
    max-width: 28rem;
    height: 100%;
    background: var(--bg-1);
    border-left: 1px solid var(--border);
    box-shadow: var(--shadow-overlay);
    overflow-y: auto;
    animation: slideIn var(--dur-slow) var(--ease-out);
  }

  @keyframes slideIn {
    from {
      transform: translateX(100%);
    }
    to {
      transform: translateX(0);
    }
  }

  .hairline {
    position: absolute;
    inset: 0 0 auto 0;
    height: 1px;
    background: linear-gradient(90deg, transparent, var(--cyan-brand), transparent);
  }

  .header {
    display: flex;
    justify-content: space-between;
    gap: var(--s-4);
    padding: var(--s-5);
    border-bottom: 1px solid var(--border);
  }

  .header h2 {
    font-size: var(--text-xl);
    font-weight: 500;
  }

  .header p {
    font-size: var(--text-sm);
    color: var(--fg-2);
    margin-top: var(--s-1);
  }

  .close {
    align-self: flex-start;
    padding: var(--s-2);
    background: transparent;
    border: none;
    color: var(--fg-2);
    cursor: pointer;
    border-radius: var(--radius-sm);
  }

  .close:hover {
    color: var(--fg-0);
  }

  .form,
  .success {
    padding: var(--s-5);
    display: flex;
    flex-direction: column;
    gap: var(--s-4);
  }

  .success {
    align-items: center;
    justify-content: center;
    text-align: center;
    min-height: 20rem;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: var(--s-2);
  }

  .field label {
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    text-transform: uppercase;
    letter-spacing: var(--track-label);
    color: var(--cyan-muted);
    font-weight: 500;
  }

  .field input,
  .field textarea {
    padding: var(--s-3) var(--s-4);
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    color: var(--fg-0);
    font-size: var(--text-base);
    transition:
      border-color var(--dur) var(--ease),
      box-shadow var(--dur) var(--ease);
  }

  .field input::placeholder,
  .field textarea::placeholder {
    color: var(--fg-3);
  }

  .field input:focus,
  .field textarea:focus {
    outline: none;
    border-color: var(--cyan-brand);
    box-shadow: 0 0 0 2px rgba(34, 229, 229, 0.15);
  }

  .field textarea {
    resize: vertical;
    min-height: 5rem;
  }

  .error {
    display: flex;
    align-items: center;
    gap: var(--s-2);
    padding: var(--s-3) var(--s-4);
    border: 1px solid var(--err-subtle);
    border-radius: var(--radius-sm);
    background: var(--err-subtle);
    color: var(--err);
    font-size: var(--text-sm);
  }

  .submit {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: var(--s-2);
    padding: var(--s-3) var(--s-5);
    border: none;
    border-radius: var(--radius-sm);
    background: linear-gradient(90deg, var(--cyan-signal), var(--cyan-brand));
    color: var(--bg-0);
    font-weight: 600;
    letter-spacing: var(--track-wide);
    cursor: pointer;
    transition:
      filter var(--dur) var(--ease),
      opacity var(--dur) var(--ease);
  }

  .submit:hover:not(:disabled) {
    filter: brightness(1.1);
  }

  .submit:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .spinner {
    width: 1rem;
    height: 1rem;
    border: 2px solid rgba(7, 8, 10, 0.3);
    border-top-color: var(--bg-0);
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  .icon,
  .icon-small {
    width: 1.25rem;
    height: 1.25rem;
  }

  .icon {
    width: 1.5rem;
    height: 1.5rem;
  }

  .icon-wrap {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 3rem;
    height: 3rem;
    border-radius: 50%;
    background: var(--cyan-subtle);
    color: var(--cyan-brand);
  }
</style>

// app/page/components/whatsapp-drawer.tsx
"use client";

import { useState, useRef, type FormEvent, type ReactNode } from "react";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Send, CheckCircle2, AlertCircle, X } from "lucide-react";
import type { Dictionary } from "@/lib/i18n/types";
import AltchaWidget from "@/app/components/altcha-widget";

type SubmitStatus = "idle" | "submitting" | "success" | "error";

function getCommsBaseUrl(): string {
  if (typeof window === "undefined") return "";
  const host = window.location.host;
  if (host.includes("rbxsystems.ch")) {
    return "https://comms.rbxsystems.ch";
  }
  return "https://comms.rbx.ia.br";
}

export function WhatsAppDrawer({
  dict,
  trigger,
  defaultOpen = false,
}: {
  dict: Dictionary;
  trigger: ReactNode;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [message, setMessage] = useState("");
  const [whatsappOptIn, setWhatsappOptIn] = useState(true);
  const [status, setStatus] = useState<SubmitStatus>("idle");
  const altchaRef = useRef<{ value: string | null }>(null);

  const commsBase = getCommsBaseUrl();
  const challengeUrl = "/api/altcha-challenge";

  const resetForm = () => {
    setName("");
    setPhone("");
    setMessage("");
    setWhatsappOptIn(true);
    setStatus("idle");
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setStatus("submitting");

    const altchaPayload = altchaRef.current?.value;
    if (!altchaPayload) {
      setStatus("error");
      return;
    }

    try {
      const res = await fetch(`${commsBase}/api/contact`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name,
          email: "",
          phone: phone || undefined,
          message: message || "Contato solicitado via WhatsApp",
          whatsappOptIn,
          altcha: altchaPayload,
        }),
      });

      if (!res.ok) throw new Error("Request failed");
      setStatus("success");
    } catch {
      setStatus("error");
    }
  };

  return (
    <Drawer open={open} onOpenChange={setOpen}>
      <DrawerTrigger asChild>{trigger}</DrawerTrigger>
      <DrawerContent className="max-h-[92vh] overflow-hidden border-white/5 bg-[#07080A]/95 backdrop-blur-md">
        <div className="relative mx-auto w-full max-w-md">
          {/* Voltage hairline */}
          <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#00FFFF]/80 to-transparent" />

          <DrawerHeader className="relative pb-2 text-left">
            <DrawerClose className="absolute right-0 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2">
              <X className="size-4 text-gray-400" />
              <span className="sr-only">Fechar</span>
            </DrawerClose>
            <DrawerTitle className="text-xl font-semibold tracking-tight text-gray-100">
              {dict.contact.whatsappLabel}
            </DrawerTitle>
            <DrawerDescription className="text-sm text-gray-400">
              {dict.contact.body}
            </DrawerDescription>
          </DrawerHeader>

          {status === "success" ? (
            <div className="relative overflow-hidden rounded-xl border border-[#06B6B6]/20 bg-[#0B0D10]/80 p-6 backdrop-blur-md m-4">
              <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#00FFFF] to-transparent" />
              <div className="flex flex-col items-center justify-center gap-4 text-center">
                <div className="flex size-12 items-center justify-center rounded-full bg-[#00FFFF]/10">
                  <CheckCircle2 className="size-6 text-[#00FFFF]" />
                </div>
                <p className="text-sm text-gray-300">{dict.contact.form.success}</p>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    resetForm();
                    setOpen(false);
                  }}
                  className="mt-1 border-[#06B6B6]/30 text-[#00FFFF] hover:bg-[#00FFFF]/10 hover:text-[#22E5E5]"
                >
                  {dict.nav.close}
                </Button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="relative space-y-5 p-4 pt-2">
              {/* Honeypot field */}
              <div className="hidden" aria-hidden="true">
                <label htmlFor="wa-website">Website</label>
                <input type="text" id="wa-website" name="website" tabIndex={-1} autoComplete="off" />
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="wa-name"
                  className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
                >
                  {dict.contact.form.name} *
                </Label>
                <Input
                  id="wa-name"
                  required
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder={dict.contact.form.namePlaceholder}
                  className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
                />
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="wa-phone"
                  className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
                >
                  WhatsApp *
                </Label>
                <Input
                  id="wa-phone"
                  type="tel"
                  required
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder={dict.contact.form.phonePlaceholder}
                  className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
                />
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="wa-message"
                  className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
                >
                  {dict.contact.form.message}
                </Label>
                <Textarea
                  id="wa-message"
                  rows={3}
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  placeholder={dict.contact.form.messagePlaceholder}
                  className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
                />
              </div>

              <div className="flex items-start gap-2 pt-1">
                <Checkbox
                  id="wa-optin"
                  checked={whatsappOptIn}
                  onCheckedChange={(checked) => setWhatsappOptIn(checked === true)}
                  className="mt-0.5 border-[#06B6B6]/50 data-[state=checked]:bg-[#00FFFF] data-[state=checked]:border-[#00FFFF] data-[state=checked]:text-[#07080A]"
                />
                <Label
                  htmlFor="wa-optin"
                  className="cursor-pointer text-sm leading-snug text-gray-400"
                >
                  {dict.contact.form.whatsappOptIn}
                </Label>
              </div>

              <div className="space-y-2">
                <AltchaWidget ref={altchaRef} challengeUrl={challengeUrl} />
              </div>

              {status === "error" && (
                <div className="flex items-center gap-2 rounded-md border border-red-500/20 bg-red-500/5 px-3 py-2 text-sm text-red-400">
                  <AlertCircle className="h-4 w-4 shrink-0" />
                  {dict.contact.form.error}
                </div>
              )}

              <DrawerFooter className="px-0 pb-2 pt-0">
                <Button
                  type="submit"
                  disabled={status === "submitting"}
                  className="w-full bg-gradient-to-r from-[#00FFFF] to-[#22E5E5] text-[#07080A] hover:from-[#22E5E5] hover:to-[#00FFFF] font-semibold tracking-wide disabled:opacity-50"
                >
                  {status === "submitting" ? (
                    <span className="flex items-center gap-2">
                      <span className="inline-block size-4 animate-spin rounded-full border-2 border-[#07080A]/30 border-t-[#07080A]" />
                      {dict.contact.form.submitting}
                    </span>
                  ) : (
                    <span className="flex items-center gap-2">
                      <Send className="size-4" />
                      {dict.contact.form.submit}
                    </span>
                  )}
                </Button>
              </DrawerFooter>
            </form>
          )}
        </div>
      </DrawerContent>
    </Drawer>
  );
}
