// app/components/altcha-widget.tsx
"use client";

import { useEffect, useRef, useState, forwardRef, useImperativeHandle } from "react";
import "altcha";
import type {} from "altcha/types/react";
import type { WidgetAttributes, WidgetMethods } from "altcha/types";

interface AltchaProps {
  challengeUrl?: string;
  onStateChange?: (ev: Event | CustomEvent) => void;
}

const AltchaWidget = forwardRef<{ value: string | null }, AltchaProps>(
  ({ challengeUrl = "/api/altcha-challenge", onStateChange }, ref) => {
    const widgetRef = useRef<WidgetAttributes & WidgetMethods & HTMLElement>(null);
    const [value, setValue] = useState<string | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        get value() {
          return value;
        },
      }),
      [value]
    );

    useEffect(() => {
      const handleStateChange = (ev: Event | CustomEvent) => {
        if ("detail" in ev) {
          setValue(ev.detail.payload || null);
          onStateChange?.(ev);
        }
      };

      const { current } = widgetRef;
      if (current) {
        current.addEventListener("statechange", handleStateChange);
        return () => current.removeEventListener("statechange", handleStateChange);
      }
    }, [onStateChange]);

    return (
      <altcha-widget
        ref={widgetRef}
        challenge={challengeUrl}
      ></altcha-widget>
    );
  }
);

AltchaWidget.displayName = "AltchaWidget";

export default AltchaWidget;

// src/lib/design/components/AltchaWidget.svelte
<script lang="ts">
  import 'altcha';
  import { createEventDispatcher, onMount } from 'svelte';

  interface Props {
    challengeurl?: string;
  }

  let { challengeurl = '/api/altcha-challenge' }: Props = $props();

  let widget: HTMLElement | undefined = $state();
  let payload = $state<string | null>(null);
  const dispatch = createEventDispatcher<{ statechange: string | null }>();

  function onStateChange(ev: Event) {
    const detail = (ev as CustomEvent).detail;
    payload = detail?.payload ?? null;
    dispatch('statechange', payload);
  }

  onMount(() => {
    const el = widget;
    el?.addEventListener('statechange', onStateChange);
    return () => el?.removeEventListener('statechange', onStateChange);
  });

  export function getValue(): string | null {
    return payload;
  }
</script>

<altcha-widget bind:this={widget} challenge={challengeurl}></altcha-widget>

<style>
  altcha-widget {
    display: block;
    min-height: 44px;
  }

  :global(altcha-widget) {
    --altcha-color-base: transparent !important;
    --altcha-color-text: var(--fg-1) !important;
    --altcha-color-border: var(--border) !important;
    --altcha-color-border-focus: var(--cyan-brand) !important;
    --altcha-color-checkbox: var(--cyan-brand) !important;
    --altcha-color-error: var(--err) !important;
    --altcha-color-spinner: var(--cyan-brand) !important;
  }
</style>
