// app/page/views/contact/contact-section.tsx
import { Mail, MessageCircle } from "lucide-react";
import ContactForm from "./contact-form";
import { WhatsAppDrawer } from "@/app/page/components/whatsapp-drawer";
import { Button } from "@/components/ui/button";
import type { Dictionary } from "@/lib/i18n/types";

const EMAIL_ADDRESS = "contact@rbxsystems.ch";

export default function ContactSection({ dict }: { dict: Dictionary }) {
  return (
    <section id="contact" className="py-16 sm:py-24">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold tracking-tight text-gray-100 sm:text-4xl">
            {dict.contact.heading}
          </h2>
          <p className="mt-3 text-gray-400">
            {dict.contact.body}
          </p>
        </div>

        <div className="grid gap-12 lg:grid-cols-5 lg:gap-16">
          <div className="space-y-8 lg:col-span-2">
            <div className="relative overflow-hidden rounded-xl border border-white/5 bg-[#0B0D10]/80 p-6 backdrop-blur-md">
              {/* Voltage hairline */}
              <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#00FFFF]/60 to-transparent" />
              {/* L-corner brackets */}
              <div className="pointer-events-none absolute inset-0">
                <div className="absolute left-0 top-0 h-3 w-3 border-l border-t border-[#00FFFF]/30" />
                <div className="absolute right-0 top-0 h-3 w-3 border-r border-t border-[#00FFFF]/30" />
                <div className="absolute bottom-0 left-0 h-3 w-3 border-b border-l border-[#00FFFF]/30" />
                <div className="absolute bottom-0 right-0 h-3 w-3 border-b border-r border-[#00FFFF]/30" />
              </div>

              <div className="relative space-y-6">
                <div>
                  <h3 className="text-[10px] font-mono font-medium uppercase tracking-[0.15em] text-[#06B6B6]">
                    {dict.contact.emailLabel}
                  </h3>
                  <a
                    href={`mailto:${EMAIL_ADDRESS}`}
                    className="mt-2 flex items-center gap-3 text-lg text-gray-100 transition-colors hover:text-[#00FFFF]"
                  >
                    <Mail className="size-5 text-[#00FFFF]/70" />
                    {EMAIL_ADDRESS}
                  </a>
                </div>

                <div>
                  <h3 className="text-[10px] font-mono font-medium uppercase tracking-[0.15em] text-[#06B6B6]">
                    {dict.contact.whatsappLabel}
                  </h3>
                  <WhatsAppDrawer
                    dict={dict}
                    trigger={
                      <Button
                        type="button"
                        variant="outline"
                        className="mt-2 inline-flex items-center gap-2 border-[#06B6B6]/30 text-[#00FFFF] hover:bg-[#00FFFF]/10 hover:text-[#22E5E5]"
                      >
                        <MessageCircle className="size-4" />
                        {dict.contact.whatsappCta}
                      </Button>
                    }
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-3">
            <ContactForm dict={dict} />
          </div>
        </div>
      </div>
    </section>
  );
}

// src/lib/design/components/ContactSection.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n';
  import ContactForm from './ContactForm.svelte';
  import WhatsAppDrawer from './WhatsAppDrawer.svelte';

  const EMAIL_ADDRESS = 'contact@rbxsystems.ch';
</script>

<section id="contact" class="contact">
  <div class="intro">
    <h2>{$_('contact.heading')}</h2>
    <p>{$_('contact.body')}</p>
  </div>

  <div class="grid">
    <div class="info">
      <div class="card">
        <div class="hairline"></div>
        <div class="corners" aria-hidden="true"></div>
        <div class="body">
          <div>
            <h3>{$_('contact.emailLabel')}</h3>
            <a href="mailto:{EMAIL_ADDRESS}" class="link">
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                class="icon-small"
              >
                <path
                  d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"
                />
                <polyline points="22,6 12,13 2,6" />
              </svg>
              {EMAIL_ADDRESS}
            </a>
          </div>

          <div>
            <h3>{$_('contact.whatsappLabel')}</h3>
            {#snippet waTrigger(open: () => void)}
              <button type="button" class="wa-button" onclick={open}>
                <svg viewBox="0 0 24 24" fill="currentColor" class="icon-small">
                  <path
                    d="M17.6 6.32A7.85 7.85 0 0 0 12 4a7.94 7.94 0 0 0-6.88 12.15l-1.08 3.94 4.03-1.06A7.93 7.93 0 0 0 20 12a7.85 7.85 0 0 0-2.4-5.68ZM12 17.5a5.46 5.46 0 0 1-2.8-.77l-.2-.12-1.66.44.44-1.62-.14-.22a5.5 5.5 0 1 1 4.36 2.29Z"
                  />
                </svg>
                {$_('contact.whatsappCta')}
              </button>
            {/snippet}
            <WhatsAppDrawer trigger={waTrigger} />
          </div>
        </div>
      </div>
    </div>

    <div class="form-col">
      <ContactForm />
    </div>
  </div>
</section>

<style>
  .contact {
    padding: var(--s-9) 0;
  }

  .intro {
    text-align: center;
    margin-bottom: var(--s-7);
  }

  .intro h2 {
    font-size: var(--text-2xl);
    font-weight: 400;
    letter-spacing: var(--track-tight);
  }

  .intro p {
    color: var(--fg-2);
    margin-top: var(--s-3);
  }

  .grid {
    display: grid;
    gap: var(--s-7);
  }

  @media (min-width: 1024px) {
    .grid {
      grid-template-columns: 2fr 3fr;
      gap: var(--s-8);
    }
  }

  .card {
    position: relative;
    overflow: hidden;
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    background: var(--bg-1);
    backdrop-filter: blur(8px);
  }

  .hairline {
    position: absolute;
    inset: 0 0 auto 0;
    height: 1px;
    background: linear-gradient(90deg, transparent, var(--cyan-brand), transparent);
    opacity: 0.6;
  }

  .corners {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }
  .corners::before,
  .corners::after {
    content: '';
    position: absolute;
    width: 0.75rem;
    height: 0.75rem;
    border-color: rgba(0, 255, 255, 0.3);
    border-style: solid;
  }
  .corners::before {
    top: 0;
    left: 0;
    border-width: 1px 0 0 1px;
  }
  .corners::after {
    bottom: 0;
    right: 0;
    border-width: 0 1px 1px 0;
  }

  .body {
    position: relative;
    padding: var(--s-6);
    display: flex;
    flex-direction: column;
    gap: var(--s-6);
  }

  .body h3 {
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    text-transform: uppercase;
    letter-spacing: var(--track-label);
    color: var(--cyan-muted);
    font-weight: 500;
  }

  .link {
    display: inline-flex;
    align-items: center;
    gap: var(--s-2);
    margin-top: var(--s-2);
    font-size: var(--text-lg);
    color: var(--fg-0);
    border-bottom: none;
  }

  .link:hover {
    color: var(--cyan-brand);
  }

  .wa-button {
    display: inline-flex;
    align-items: center;
    gap: var(--s-2);
    margin-top: var(--s-2);
    padding: var(--s-2) var(--s-4);
    background: transparent;
    border: 1px solid var(--cyan-dim);
    border-radius: var(--radius-sm);
    color: var(--cyan-brand);
    font-family: var(--font-sans);
    font-size: var(--text-sm);
    cursor: pointer;
    transition:
      background var(--dur) var(--ease),
      border-color var(--dur) var(--ease);
  }

  .wa-button:hover {
    background: var(--cyan-subtle);
    border-color: var(--cyan-brand);
    color: var(--cyan-signal);
  }

  .icon-small {
    width: 1.25rem;
    height: 1.25rem;
    flex-shrink: 0;
  }
</style>
