// app/page/views/contact/contact-form.tsx
"use client";

import { useState, useRef, type FormEvent } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Send, CheckCircle2, AlertCircle } from "lucide-react";
import type { Dictionary } from "@/lib/i18n/types";
import AltchaWidget from "@/app/components/altcha-widget";

type SubmitStatus = "idle" | "submitting" | "success" | "error";

function getCommsBaseUrl(): string {
  if (typeof window === "undefined") return "";
  const host = window.location.host;
  if (host.includes("rbxsystems.ch")) {
    return "https://comms.rbxsystems.ch";
  }
  return "https://comms.rbx.ia.br";
}

export default function ContactForm({ dict }: { dict: Dictionary }) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [message, setMessage] = useState("");
  const [whatsappOptIn, setWhatsappOptIn] = useState(false);
  const [status, setStatus] = useState<SubmitStatus>("idle");
  const altchaRef = useRef<{ value: string | null }>(null);

  const commsBase = getCommsBaseUrl();
  const challengeUrl = "/api/altcha-challenge";

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setStatus("submitting");

    const altchaPayload = altchaRef.current?.value;
    if (!altchaPayload) {
      setStatus("error");
      return;
    }

    try {
      const res = await fetch(`${commsBase}/api/contact`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name,
          email,
          phone: phone || undefined,
          message,
          whatsappOptIn,
          altcha: altchaPayload,
        }),
      });

      if (!res.ok) throw new Error("Request failed");
      setStatus("success");
      setName("");
      setEmail("");
      setPhone("");
      setMessage("");
      setWhatsappOptIn(false);
    } catch {
      setStatus("error");
    }
  };

  if (status === "success") {
    return (
      <div className="relative overflow-hidden rounded-xl border border-[#06B6B6]/20 bg-[#07080A]/80 backdrop-blur-md">
        {/* Voltage hairline */}
        <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#00FFFF] to-transparent" />
        {/* L-corner brackets */}
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute left-0 top-0 h-4 w-4 border-l border-t border-[#00FFFF]/30" />
          <div className="absolute right-0 top-0 h-4 w-4 border-r border-t border-[#00FFFF]/30" />
          <div className="absolute bottom-0 left-0 h-4 w-4 border-b border-l border-[#00FFFF]/30" />
          <div className="absolute bottom-0 right-0 h-4 w-4 border-b border-r border-[#00FFFF]/30" />
        </div>

        <div className="flex flex-col items-center justify-center gap-4 p-8 text-center">
          <div className="flex size-12 items-center justify-center rounded-full bg-[#00FFFF]/10">
            <CheckCircle2 className="size-6 text-[#00FFFF]" />
          </div>
          <p className="text-sm text-gray-300">{dict.contact.form.success}</p>
          <Button
            variant="outline"
            size="sm"
            onClick={() => setStatus("idle")}
            className="mt-1 border-[#06B6B6]/30 text-[#00FFFF] hover:bg-[#00FFFF]/10 hover:text-[#22E5E5]"
          >
            {dict.contact.form.submit}
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="relative overflow-hidden rounded-xl border border-white/5 bg-[#0B0D10]/90 backdrop-blur-md">
      {/* Voltage hairline sweep */}
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#00FFFF]/80 to-transparent" />

      {/* L-corner brackets */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute left-0 top-0 h-4 w-4 border-l border-t border-[#00FFFF]/30" />
        <div className="absolute right-0 top-0 h-4 w-4 border-r border-t border-[#00FFFF]/30" />
        <div className="absolute bottom-0 left-0 h-4 w-4 border-b border-l border-[#00FFFF]/30" />
        <div className="absolute bottom-0 right-0 h-4 w-4 border-b border-r border-[#00FFFF]/30" />
      </div>

      <form onSubmit={handleSubmit} className="relative space-y-5 p-6 sm:p-8">
        {/* Honeypot field — hidden from humans, visible to bots */}
        <div className="hidden" aria-hidden="true">
          <label htmlFor="website">Website</label>
          <input type="text" id="website" name="website" tabIndex={-1} autoComplete="off" />
        </div>

        <div className="grid gap-5 sm:grid-cols-2">
          <div className="space-y-2">
            <Label
              htmlFor="name"
              className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
            >
              {dict.contact.form.name} *
            </Label>
            <Input
              id="name"
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder={dict.contact.form.namePlaceholder}
              className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
            />
          </div>

          <div className="space-y-2">
            <Label
              htmlFor="email"
              className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
            >
              {dict.contact.form.email} *
            </Label>
            <Input
              id="email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={dict.contact.form.emailPlaceholder}
              className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
            />
          </div>
        </div>

        <div className="space-y-2">
          <Label
            htmlFor="phone"
            className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
          >
            {dict.contact.form.phone}
          </Label>
          <Input
            id="phone"
            type="tel"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
            placeholder={dict.contact.form.phonePlaceholder}
            className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
          />
        </div>

        <div className="space-y-2">
          <Label
            htmlFor="message"
            className="text-[10px] font-medium uppercase tracking-[0.15em] text-[#06B6B6] font-mono"
          >
            {dict.contact.form.message} *
          </Label>
          <Textarea
            id="message"
            required
            rows={4}
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            placeholder={dict.contact.form.messagePlaceholder}
            className="border-white/10 bg-white/[0.03] text-gray-100 placeholder:text-gray-600 focus-visible:ring-[#00FFFF]/40 focus-visible:border-[#00FFFF]/50"
          />
        </div>

        <div className="flex items-start gap-2 pt-1">
          <Checkbox
            id="whatsappOptIn"
            checked={whatsappOptIn}
            onCheckedChange={(checked) => setWhatsappOptIn(checked === true)}
            className="mt-0.5 border-[#06B6B6]/50 data-[state=checked]:bg-[#00FFFF] data-[state=checked]:border-[#00FFFF] data-[state=checked]:text-[#07080A]"
          />
          <Label
            htmlFor="whatsappOptIn"
            className="cursor-pointer text-sm leading-snug text-gray-400"
          >
            {dict.contact.form.whatsappOptIn}
          </Label>
        </div>

        <div className="space-y-2">
          <AltchaWidget ref={altchaRef} challengeUrl={challengeUrl} />
        </div>

        {status === "error" && (
          <div className="flex items-center gap-2 rounded-md border border-red-500/20 bg-red-500/5 px-3 py-2 text-sm text-red-400">
            <AlertCircle className="h-4 w-4 shrink-0" />
            {dict.contact.form.error}
          </div>
        )}

        <Button
          type="submit"
          disabled={status === "submitting"}
          className="w-full bg-gradient-to-r from-[#00FFFF] to-[#22E5E5] text-[#07080A] hover:from-[#22E5E5] hover:to-[#00FFFF] font-semibold tracking-wide disabled:opacity-50"
        >
          {status === "submitting" ? (
            <span className="flex items-center gap-2">
              <span className="inline-block size-4 animate-spin rounded-full border-2 border-[#07080A]/30 border-t-[#07080A]" />
              {dict.contact.form.submitting}
            </span>
          ) : (
            <span className="flex items-center gap-2">
              <Send className="size-4" />
              {dict.contact.form.submit}
            </span>
          )}
        </Button>
      </form>
    </div>
  );
}

// src/lib/design/components/ContactForm.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n';
  import { getCommsBaseUrl } from '$lib/api/comms';
  import AltchaWidget from './AltchaWidget.svelte';

  type Status = 'idle' | 'submitting' | 'success' | 'error';

  let name = $state('');
  let email = $state('');
  let phone = $state('');
  let message = $state('');
  let whatsappOptIn = $state(false);
  let website = $state(''); // honeypot
  let altchaPayload = $state<string | null>(null);
  let status = $state<Status>('idle');

  const commsBase = getCommsBaseUrl();
  const challengeUrl = `${commsBase}/api/altcha-challenge`;

  async function handleSubmit(ev: SubmitEvent) {
    ev.preventDefault();

    if (!altchaPayload) {
      status = 'error';
      return;
    }

    status = 'submitting';

    try {
      const res = await fetch(`${commsBase}/api/contact`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          email,
          phone: phone || undefined,
          message,
          whatsapp_opt_in: whatsappOptIn,
          altcha: altchaPayload,
          website,
          source: 'site',
          language: $_('common.languageCode') ?? 'pt'
        })
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      status = 'success';
      name = '';
      email = '';
      phone = '';
      message = '';
      whatsappOptIn = false;
      altchaPayload = null;
    } catch {
      status = 'error';
    }
  }
</script>

{#if status === 'success'}
  <div class="success-card">
    <div class="hairline"></div>
    <div class="corners" aria-hidden="true"></div>
    <div class="content">
      <div class="icon-wrap">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icon">
          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
          <polyline points="22 4 12 14.01 9 11.01" />
        </svg>
      </div>
      <p>{$_('contact.form.success')}</p>
      <button type="button" class="rbx-cta" onclick={() => (status = 'idle')}>
        {$_('contact.form.submit')}
      </button>
    </div>
  </div>
{:else}
  <form class="form" onsubmit={handleSubmit}>
    <div class="hairline"></div>
    <div class="corners" aria-hidden="true"></div>

    <!-- Honeypot — hidden from humans -->
    <div class="honeypot" aria-hidden="true">
      <label for="website">Website</label>
      <input
        type="text"
        id="website"
        name="website"
        tabindex="-1"
        autocomplete="off"
        bind:value={website}
      />
    </div>

    <div class="row">
      <div class="field">
        <label for="contact-name">{$_('contact.form.name')} *</label>
        <input
          id="contact-name"
          type="text"
          required
          bind:value={name}
          placeholder={$_('contact.form.namePlaceholder')}
        />
      </div>
      <div class="field">
        <label for="contact-email">{$_('contact.form.email')} *</label>
        <input
          id="contact-email"
          type="email"
          required
          bind:value={email}
          placeholder={$_('contact.form.emailPlaceholder')}
        />
      </div>
    </div>

    <div class="field">
      <label for="contact-phone">{$_('contact.form.phone')}</label>
      <input
        id="contact-phone"
        type="tel"
        bind:value={phone}
        placeholder={$_('contact.form.phonePlaceholder')}
      />
    </div>

    <div class="field">
      <label for="contact-message">{$_('contact.form.message')} *</label>
      <textarea
        id="contact-message"
        rows="4"
        required
        bind:value={message}
        placeholder={$_('contact.form.messagePlaceholder')}
      ></textarea>
    </div>

    <div class="checkbox">
      <input id="contact-whatsapp" type="checkbox" bind:checked={whatsappOptIn} />
      <label for="contact-whatsapp">{$_('contact.form.whatsappOptIn')}</label>
    </div>

    <AltchaWidget
      challengeurl={challengeUrl}
      on:statechange={(ev) => (altchaPayload = ev.detail)}
    />

    {#if status === 'error'}
      <div class="error" role="alert">
        <svg
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          class="icon-small"
        >
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        <span>{$_('contact.form.error')}</span>
      </div>
    {/if}

    <button type="submit" class="submit" disabled={status === 'submitting'}>
      {#if status === 'submitting'}
        <span class="spinner"></span>
        <span>{$_('contact.form.submitting')}</span>
      {:else}
        <svg
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          class="icon-small"
        >
          <line x1="22" y1="2" x2="11" y2="13" />
          <polygon points="22 2 15 22 11 13 2 9 22 2" />
        </svg>
        <span>{$_('contact.form.submit')}</span>
      {/if}
    </button>
  </form>
{/if}

<style>
  .form,
  .success-card {
    position: relative;
    overflow: hidden;
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    background: var(--bg-1);
    backdrop-filter: blur(8px);
  }

  .hairline {
    position: absolute;
    inset: 0 0 auto 0;
    height: 1px;
    background: linear-gradient(90deg, transparent, var(--cyan-brand), transparent);
    opacity: 0.8;
  }

  .corners {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }
  .corners::before,
  .corners::after {
    content: '';
    position: absolute;
    width: 1rem;
    height: 1rem;
    border-color: rgba(0, 255, 255, 0.3);
    border-style: solid;
  }
  .corners::before {
    top: 0;
    left: 0;
    border-width: 1px 0 0 1px;
  }
  .corners::after {
    bottom: 0;
    right: 0;
    border-width: 0 1px 1px 0;
  }

  .form {
    padding: var(--s-6);
    display: flex;
    flex-direction: column;
    gap: var(--s-4);
  }

  .row {
    display: grid;
    gap: var(--s-4);
  }

  @media (min-width: 640px) {
    .row {
      grid-template-columns: 1fr 1fr;
    }
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: var(--s-2);
  }

  .field label,
  .checkbox label {
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    text-transform: uppercase;
    letter-spacing: var(--track-label);
    color: var(--cyan-muted);
    font-weight: 500;
  }

  .field input,
  .field textarea {
    padding: var(--s-3) var(--s-4);
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    color: var(--fg-0);
    font-size: var(--text-base);
    transition:
      border-color var(--dur) var(--ease),
      box-shadow var(--dur) var(--ease);
  }

  .field input::placeholder,
  .field textarea::placeholder {
    color: var(--fg-3);
  }

  .field input:focus,
  .field textarea:focus {
    outline: none;
    border-color: var(--cyan-brand);
    box-shadow: 0 0 0 2px rgba(34, 229, 229, 0.15);
  }

  .field textarea {
    resize: vertical;
    min-height: 6rem;
  }

  .checkbox {
    display: flex;
    align-items: flex-start;
    gap: var(--s-2);
  }

  .checkbox input {
    margin-top: 0.15rem;
    width: 1rem;
    height: 1rem;
    accent-color: var(--cyan-brand);
  }

  .honeypot {
    position: absolute;
    left: -9999px;
    width: 1px;
    height: 1px;
    overflow: hidden;
  }

  .error {
    display: flex;
    align-items: center;
    gap: var(--s-2);
    padding: var(--s-3) var(--s-4);
    border: 1px solid var(--err-subtle);
    border-radius: var(--radius-sm);
    background: var(--err-subtle);
    color: var(--err);
    font-size: var(--text-sm);
  }

  .submit {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: var(--s-2);
    padding: var(--s-3) var(--s-5);
    border: none;
    border-radius: var(--radius-sm);
    background: linear-gradient(90deg, var(--cyan-signal), var(--cyan-brand));
    color: var(--bg-0);
    font-weight: 600;
    letter-spacing: var(--track-wide);
    cursor: pointer;
    transition:
      filter var(--dur) var(--ease),
      opacity var(--dur) var(--ease);
  }

  .submit:hover:not(:disabled) {
    filter: brightness(1.1);
  }

  .submit:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .spinner {
    width: 1rem;
    height: 1rem;
    border: 2px solid rgba(7, 8, 10, 0.3);
    border-top-color: var(--bg-0);
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  .success-card {
    padding: var(--s-7);
  }

  .success-card .content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: var(--s-4);
    text-align: center;
  }

  .icon-wrap {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 3rem;
    height: 3rem;
    border-radius: 50%;
    background: var(--cyan-subtle);
    color: var(--cyan-brand);
  }

  .icon,
  .icon-small {
    width: 1.25rem;
    height: 1.25rem;
  }

  .icon {
    width: 1.5rem;
    height: 1.5rem;
  }
</style>
