// app/page/views/footer/footer.tsx
import Image from "next/image";
import Link from "next/link";
import { SiLinkedin, SiGithub } from "react-icons/si";
import { FaWhatsapp } from "react-icons/fa";
import { Mail, MessageCircle } from "lucide-react";
import type { Dictionary } from "@/lib/i18n/types";

const EMAIL = "contact@rbxsystems.ch";
const CONTACT_HASH = "/#contact";
const STATUS_URL = "https://status.rbxsystems.ch";

export default function Footer({ dict }: { dict: Dictionary }) {
  const sections = [
    {
      title: dict.footer.sections.company,
      links: [
        { label: dict.footer.links.aboutUs, href: "/#about-us" },
        { label: dict.footer.links.team, href: "/#team" },
        { label: dict.footer.links.products, href: "/produtos" },
        { label: "Atelier", href: "/atelier" },
      ],
    },
    {
      title: dict.footer.sections.resources,
      links: [
        { label: dict.footer.links.journal, href: "/journal" },
        { label: dict.footer.links.changelog, href: "/changelog" },
        { label: dict.footer.links.cases, href: "/cases" },
        { label: dict.footer.links.newsroom, href: "/newsroom" },
        { label: dict.footer.links.trust, href: "/trust" },
        { label: dict.footer.links.status, href: STATUS_URL },
      ],
    },
    {
      title: dict.footer.sections.contact,
      links: [
        { label: EMAIL, href: `mailto:${EMAIL}`, icon: Mail },
        { label: "WhatsApp", href: CONTACT_HASH, icon: MessageCircle },
        { label: dict.footer.links.github, href: "https://github.com/rbxrobotica", icon: SiGithub },
        { label: dict.footer.links.linkedin, href: "https://linkedin.com/company/rbxrobotica", icon: SiLinkedin },
      ],
    },
  ];

  const socialLinks = [
    { icon: SiGithub, href: "https://github.com/rbxrobotica" },
    { icon: SiLinkedin, href: "https://linkedin.com/company/rbxrobotica" },
    { icon: FaWhatsapp, href: CONTACT_HASH },
  ];

  return (
    <footer className="mt-32 bg-[#1D1D22] border-t border-[#1D1D22] py-10" id="footer">
      <div className="mx-auto w-full max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col gap-12 lg:flex-row lg:items-start lg:justify-between lg:gap-16">
          <div className="mx-auto w-full max-w-sm text-center lg:mx-0 lg:w-1/3 lg:max-w-none lg:text-left">
            <div className="flex justify-center lg:justify-start">
              <Image
                src="/api/assets/ui/bitmap.svg"
                alt="RBX Robotica"
                width={50}
                height={50}
                className="mb-4"
                unoptimized
              />
            </div>
            <h2 className="text-xl font-bold text-gray-100">RBX Systems</h2>
            <p className="mt-2 text-gray-400">
              {dict.footer.description}
            </p>
          </div>

          <div className="grid w-full gap-8 text-center sm:grid-cols-2 sm:text-left lg:w-2/3 lg:grid-cols-3">
            {sections.map((section, index) => (
              <div key={index}>
                <h3 className="font-medium text-gray-100">{section.title}</h3>
                <ul className="mt-4 space-y-2 text-gray-400">
                  {section.links.map((link, idx) => {
                    const Icon = "icon" in link ? link.icon : null;
                    return (
                      <li key={idx}>
                        {"icon" in link ? (
                          <a href={link.href} className="inline-flex items-center gap-2 break-words hover:text-gray-100" target={link.href.startsWith("http") ? "_blank" : undefined} rel={link.href.startsWith("http") ? "noopener noreferrer" : undefined}>
                            {Icon && <Icon className="h-4 w-4 shrink-0" />}
                            {link.label}
                          </a>
                        ) : (
                          <Link href={link.href} className="break-words hover:text-gray-100">
                            {link.label}
                          </Link>
                        )}
                      </li>
                    );
                  })}
                </ul>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-8 flex justify-center gap-6 text-gray-400 lg:justify-start">
          {socialLinks.map(({ icon: Icon, href }, index) => (
            <a key={index} href={href} className="hover:text-gray-100" target="_blank" rel="noopener noreferrer">
              <Icon className="w-6 h-6" />
            </a>
          ))}
        </div>

        <div className="mt-10 border-t border-gray-600 pt-6 text-center text-gray-400">
          <p>&copy; {new Date().getFullYear()} RBX Systems. {dict.footer.copyright}</p>
        </div>
      </div>
    </footer>
  );
}

// src/lib/design/components/Footer.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n';

  const year = new Date().getFullYear();
</script>

<footer class="footer">
  <div class="footer-inner">
    <div class="footer-brand">
      <img src="/brand/rbx-mark.svg" alt="" width="28" height="28" />
      <span class="footer-name">RBX Systems</span>
      <p class="rbx-caption">{$_('footer.description')}</p>
    </div>

    <div class="footer-columns">
      <div>
        <h3 class="rbx-label">{$_('footer.companyTitle')}</h3>
        <ul>
          <li><a href="/">{$_('nav.home')}</a></li>
          <li><a href="/solucoes">{$_('nav.solutions')}</a></li>
          <li><a href="/produtos">{$_('nav.products')}</a></li>
          <li><a href="/atelier">{$_('nav.atelier')}</a></li>
        </ul>
      </div>
      <div>
        <h3 class="rbx-label">{$_('footer.resourcesTitle')}</h3>
        <ul>
          <li><a href="/journal">{$_('nav.journal')}</a></li>
          <li><a href="/changelog">{$_('nav.changelog')}</a></li>
          <li><a href="/cases">{$_('nav.cases')}</a></li>
          <li><a href="/newsroom">{$_('nav.newsroom')}</a></li>
          <li><a href="/trust">{$_('nav.trust')}</a></li>
        </ul>
      </div>
      <div>
        <h3 class="rbx-label">{$_('footer.contactTitle')}</h3>
        <ul>
          <li><a href="mailto:contact@rbxsystems.ch">contact@rbxsystems.ch</a></li>
          <li><a href="https://github.com/rbxrobotica" target="_blank" rel="noopener noreferrer">GitHub</a></li>
          <li><a href="https://linkedin.com/company/rbxrobotica" target="_blank" rel="noopener noreferrer">LinkedIn</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <p class="rbx-caption">&copy; {year} RBX Systems. {$_('footer.rights')}</p>
  </div>
</footer>

<style>
  .footer {
    margin-top: auto;
    border-top: 1px solid var(--border);
    background: var(--bg-1);
    padding: var(--s-7) 0 var(--s-5);
  }
  .footer-inner {
    max-width: var(--content-w);
    margin: 0 auto;
    padding: 0 var(--gutter);
    display: grid;
    gap: var(--s-6);
    grid-template-columns: 1fr;
  }
  @media (min-width: 768px) {
    .footer-inner {
      grid-template-columns: 1fr 2fr;
    }
  }
  .footer-brand {
    display: flex;
    flex-direction: column;
    gap: var(--s-2);
  }
  .footer-name {
    font-size: var(--text-xl);
    font-weight: 600;
  }
  .footer-columns {
    display: grid;
    gap: var(--s-5);
    grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));
  }
  .footer-columns h3 {
    margin-bottom: var(--s-3);
  }
  .footer-columns ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: var(--s-2);
  }
  .footer-columns a {
    color: var(--fg-1);
    font-size: var(--text-sm);
  }
  .footer-bottom {
    max-width: var(--content-w);
    margin: var(--s-6) auto 0;
    padding: var(--s-4) var(--gutter) 0;
    border-top: 1px solid var(--border);
  }
</style>
